
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 9;
  public static final int DOSPUNTOS = 4;
  public static final int PUNTOYCOMA = 3;
  public static final int GRAPHPIE = 39;
  public static final int DOUBLE = 12;
  public static final int RESTA = 23;
  public static final int GRAPHBAR = 38;
  public static final int FIN = 6;
  public static final int TITULOY = 45;
  public static final int TITULOX = 44;
  public static final int EJEY = 43;
  public static final int EJEX = 42;
  public static final int IGUAL = 2;
  public static final int COLUMN = 33;
  public static final int ARROBA = 19;
  public static final int CADENA_F = 8;
  public static final int TITULO = 36;
  public static final int CERRARCORCHETES = 16;
  public static final int GUION = 13;
  public static final int SUMA = 22;
  public static final int MIN = 32;
  public static final int MEDIANA = 28;
  public static final int EOF = 0;
  public static final int ARREGLO = 18;
  public static final int error = 1;
  public static final int COMA = 5;
  public static final int VALUES = 35;
  public static final int MODULO = 26;
  public static final int MODA = 29;
  public static final int CADENACHAR = 17;
  public static final int ABRIRPARENTESIS = 20;
  public static final int ABRIRCORCHETES = 15;
  public static final int PROGRAMPAL = 14;
  public static final int VARIANZA = 30;
  public static final int MEDIA = 27;
  public static final int CERRARPARENTESIS = 21;
  public static final int EXEC = 34;
  public static final int LABEL = 37;
  public static final int DIVISION = 25;
  public static final int MAX = 31;
  public static final int HISTOGRAM = 41;
  public static final int GRAPHLINE = 40;
  public static final int VAR = 11;
  public static final int PRINT = 10;
  public static final int CONSOLE = 7;
  public static final int MULTIPLICACION = 24;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IGUAL",
  "PUNTOYCOMA",
  "DOSPUNTOS",
  "COMA",
  "FIN",
  "CONSOLE",
  "CADENA_F",
  "NUMERO",
  "PRINT",
  "VAR",
  "DOUBLE",
  "GUION",
  "PROGRAMPAL",
  "ABRIRCORCHETES",
  "CERRARCORCHETES",
  "CADENACHAR",
  "ARREGLO",
  "ARROBA",
  "ABRIRPARENTESIS",
  "CERRARPARENTESIS",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "MODULO",
  "MEDIA",
  "MEDIANA",
  "MODA",
  "VARIANZA",
  "MAX",
  "MIN",
  "COLUMN",
  "EXEC",
  "VALUES",
  "TITULO",
  "LABEL",
  "GRAPHBAR",
  "GRAPHPIE",
  "GRAPHLINE",
  "HISTOGRAM",
  "EJEX",
  "EJEY",
  "TITULOX",
  "TITULOY"
  };
}

