
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 9;
  public static final int DOSPUNTOS = 4;
  public static final int PUNTOYCOMA = 3;
  public static final int GRAPHPIE = 41;
  public static final int DOUBLE = 14;
  public static final int RESTA = 25;
  public static final int PALABRA_I = 48;
  public static final int GRAPHBAR = 40;
  public static final int FIN = 6;
  public static final int TITULOY = 47;
  public static final int OPENCOM = 11;
  public static final int TITULOX = 46;
  public static final int EJEY = 45;
  public static final int EJEX = 44;
  public static final int IGUAL = 2;
  public static final int COLUMN = 35;
  public static final int ARROBA = 21;
  public static final int CADENA_F = 8;
  public static final int TITULO = 38;
  public static final int CERRARCORCHETES = 18;
  public static final int GUION = 15;
  public static final int SUMA = 24;
  public static final int MIN = 34;
  public static final int CLOSECOM = 12;
  public static final int MEDIANA = 30;
  public static final int EOF = 0;
  public static final int ARREGLO = 20;
  public static final int error = 1;
  public static final int COMA = 5;
  public static final int VALUES = 37;
  public static final int MODULO = 28;
  public static final int MODA = 31;
  public static final int CADENACHAR = 19;
  public static final int ABRIRPARENTESIS = 22;
  public static final int ABRIRCORCHETES = 17;
  public static final int PROGRAMPAL = 16;
  public static final int VARIANZA = 32;
  public static final int MEDIA = 29;
  public static final int CERRARPARENTESIS = 23;
  public static final int EXEC = 36;
  public static final int LABEL = 39;
  public static final int DIVISION = 27;
  public static final int MAX = 33;
  public static final int HISTOGRAM = 43;
  public static final int GRAPHLINE = 42;
  public static final int VAR = 13;
  public static final int PRINT = 10;
  public static final int CONSOLE = 7;
  public static final int MULTIPLICACION = 26;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IGUAL",
  "PUNTOYCOMA",
  "DOSPUNTOS",
  "COMA",
  "FIN",
  "CONSOLE",
  "CADENA_F",
  "NUMERO",
  "PRINT",
  "OPENCOM",
  "CLOSECOM",
  "VAR",
  "DOUBLE",
  "GUION",
  "PROGRAMPAL",
  "ABRIRCORCHETES",
  "CERRARCORCHETES",
  "CADENACHAR",
  "ARREGLO",
  "ARROBA",
  "ABRIRPARENTESIS",
  "CERRARPARENTESIS",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "MODULO",
  "MEDIA",
  "MEDIANA",
  "MODA",
  "VARIANZA",
  "MAX",
  "MIN",
  "COLUMN",
  "EXEC",
  "VALUES",
  "TITULO",
  "LABEL",
  "GRAPHBAR",
  "GRAPHPIE",
  "GRAPHLINE",
  "HISTOGRAM",
  "EJEX",
  "EJEY",
  "TITULOX",
  "TITULOY",
  "PALABRA_I"
  };
}

